---
title: "Exam 1"
draft: false
linktitle: "Exam 1"
date: "2020-06-08"
menu:
  assignments:
    parent: Exams
    weight: 3
type: docs
#output:
#  blogdown::html_page:
#    toc: true
---

{{% alert note %}}
Check back later for more details about the exact logistics of the exam. Until then, the resources to help you study are already available and will not change.
{{% /alert %}}

# Concepts Study Guide

- [<i class="fas fa-file-pdf"></i> Download PDF](/examprep/exam_1_study_guide.pdf)

Note that we skipped some excess content about preferences this semester, so some things on the study guide (like assumptions about preferences, assumptions about indifference curves, indifference curves for non-goods -- the graph on page 5, steepness --graph on page 7--but know complements & substitutes!), you can safely ignore.

# "Practice" Exam

- [<i class="fas fa-file-pdf"></i> Download Old Exam 1](/examprep/Exam1.pdf)

Above, you have a previous semester's actual exam. Use it to get a sense of what questions are asked, the format, and how many. 

Please note that this semester we skipped some things about preferences, so you would not be responsible for questions asking about them. In this old exam, that means questions 5 and 9. Though you should still be able to deduce the answers!

**Be aware: this is pre-Covid when exams were taken in person on paper. The online nature of this semester will significantly affect the questions asked!** Questions draw from topics in Unit 1, and note that **just because topics or questions were not in the practice exam does NOT mean they may not show up on your exam.**^[I hope that this is obvious. I write this to ensure there is no misunderstanding.] Aside from minor extensions, no mathematical problem on any exam should be something you have not seen in some form before. 

Look at the practice exam *before* our Review day. I will post the answer key during the weekend. I am happy to discuss other individual answers and strategies during Office Hours.

# My Advice

Make sure you do all of the homework problems and learn from the answer keys to the homeworks, as well as the in-class practice problems. All of the math problems are largely in the style of the homework questions. While some of the questions should be novel applications, conceptual questions on homeworks will get you in the right headspace to think about answering a question on an exam.^[The point of exams is to *apply* what you've learned, not to literally regurgitate it! Or, at least, it should be.]